select * from employee1;
select emp_name,Role from employee1;
select emp_name,Join_Date from employee1;
select emp_name,emp_no from employee1;
select emp_name,Dept_Id from employee1;
select emp_name,salary from employee1;
select emp_name,Bonus from employee1;
select emp_name,Blood_Group from employee1;
select emp_name,Gender from employee1;
select emp_name,DOB from employee1;
select emp_name,salary*12 as annual_salary from employee1;
select emp_name,salary+Bonus as total_compensation from employee1;
select emp_name,salary*6 as half_year_salary from employee1;
select emp_name,salary*1.10+salary as incremented_salary from employee1;
select emp_name,salary*(25/100) as reduced_salary from employee1;
select emp_name,salary+2000 as bonus_salary from employee1;
select emp_name,salary-100 as penality_reduced_salary from employee1;
select emp_name,salary+500*12 as hike_salary from employee1;
select emp_name,salary+2400 as annual_bonus_salary from employee1;
select count(dept_id) from employee1;
select count(role) from employee1;
select count(distinct dept_id) from employee1;
select count(distinct role) from employee1;